const COUNTRY_TO_ISO: Record<string, string> = {
  // North America
  "united states": "US",
  "united states of america": "US",
  usa: "US",
  us: "US",
  "u.s.": "US",
  "u.s.a.": "US",
  america: "US",
  canada: "CA",
  mexico: "MX",

  // United Kingdom & Ireland
  "united kingdom": "GB",
  uk: "GB",
  "u.k.": "GB",
  "great britain": "GB",
  britain: "GB",
  england: "GB",
  scotland: "GB",
  wales: "GB",
  ireland: "IE",

  // Continental Europe
  germany: "DE",
  france: "FR",
  italy: "IT",
  spain: "ES",
  netherlands: "NL",
  "the netherlands": "NL",
  belgium: "BE",
  switzerland: "CH",
  sweden: "SE",
  norway: "NO",
  denmark: "DK",
  finland: "FI",
  austria: "AT",
  poland: "PL",
  portugal: "PT",
  greece: "GR",
  "czech republic": "CZ",
  czechia: "CZ",
  hungary: "HU",
  romania: "RO",
  bulgaria: "BG",
  luxembourg: "LU",
  iceland: "IS",
  estonia: "EE",
  lithuania: "LT",
  latvia: "LV",
  cyprus: "CY",
  malta: "MT",
  slovenia: "SI",
  slovakia: "SK",
  croatia: "HR",
  serbia: "RS",

  // Middle East
  "united arab emirates": "AE",
  uae: "AE",
  "u.a.e.": "AE",
  "saudi arabia": "SA",
  ksa: "SA",
  qatar: "QA",
  kuwait: "KW",
  bahrain: "BH",
  oman: "OM",
  israel: "IL",
  turkey: "TR",
  türkiye: "TR",
  jordan: "JO",
  lebanon: "LB",

  // Africa
  egypt: "EG",
  "south africa": "ZA",
  kenya: "KE",
  nigeria: "NG",
  morocco: "MA",
  tunisia: "TN",
  algeria: "DZ",
  ghana: "GH",
  tanzania: "TZ",
  uganda: "UG",
  ethiopia: "ET",
  rwanda: "RW",
  mauritius: "MU",
  senegal: "SN",

  // Asia
  india: "IN",
  singapore: "SG",
  "hong kong": "HK",
  china: "CN",
  "people's republic of china": "CN",
  japan: "JP",
  "south korea": "KR",
  korea: "KR",
  taiwan: "TW",
  malaysia: "MY",
  indonesia: "ID",
  thailand: "TH",
  vietnam: "VN",
  philippines: "PH",
  pakistan: "PK",
  bangladesh: "BD",
  "sri lanka": "LK",
  nepal: "NP",
  cambodia: "KH",
  myanmar: "MM",
  burma: "MM",

  // Oceania
  australia: "AU",
  "new zealand": "NZ",
  fiji: "FJ",

  // South & Central America
  brazil: "BR",
  argentina: "AR",
  chile: "CL",
  colombia: "CO",
  peru: "PE",
  venezuela: "VE",
  uruguay: "UY",
  ecuador: "EC",
  bolivia: "BO",
  paraguay: "PY",
  panama: "PA",
  "costa rica": "CR",
  "dominican republic": "DO",
  jamaica: "JM",
  cuba: "CU",
  bahamas: "BS",
  bermuda: "BM",
  "cayman islands": "KY",

  // Russia / CIS
  russia: "RU",
  "russian federation": "RU",
  ukraine: "UA",
  belarus: "BY",
  kazakhstan: "KZ",
  uzbekistan: "UZ",
  azerbaijan: "AZ",
  georgia: "GE",
  armenia: "AM",
};

export function getCountryFlag(country: string | null | undefined): string {
  if (!country) return "";
  const code = COUNTRY_TO_ISO[country.trim().toLowerCase()];
  if (!code) return "";
  return code
    .toUpperCase()
    .split("")
    .map((c) => String.fromCodePoint(0x1f1a5 + c.charCodeAt(0)))
    .join("");
}
